import Head from "next/head";
import HomePage from "@/src/PageComponents/Home";
import HeaderLayout from "@/src/Layouts/header";
import { wrapper } from "@/src/redux/store";
import { getChapterAction } from "@/src/redux/actions/actions";
import { END } from "redux-saga";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <HeaderLayout>
        <HomePage />
      </HeaderLayout>
    </>
  );
};
export const getServerSideProps = wrapper.getServerSideProps((store) => async({req, res, ...etc}) => {
  console.log(store);
  // if (!store.getState().chapterData) {
  //  store.dispatch(getChapterAction());
  //   console.log("ending saga on server now...");
  //  store.dispatch(END);
  // } 
  // await store.sagaTask.toPromise();

});
export default Home;
